blog/urls.py
from django.urls import path 

from blog.views import (
	BlogPageView, 
	# SearchResultsListView, 
    # CategoryPageView,
	PostDetailView,
)


app_name = 'blog'
urlpatterns = [

 	path('blog/', BlogPageView.as_view(), name='blog'),
 	path('blog/<slug:slug>', PostDetailView.as_view(), name='blog_post_detail'),
 	# path('search/', SearchResultsListView.as_view(), name='search_results'),
	# path('category/<int:pk>', CategoryPageView.as_view(), name='category'),

]

courses/urls.py
from django.urls import path

from .views import (
    ManageCourseListView,
    CourseCreateView,
    CourseUpdateView,
    CourseDeleteView,
    CourseModuleUpdateView,
    ModuleContentListView,
    ModuleOrderView,
    ContentOrderView,
    CourseListView,
    CourseDetailView,
    IndexView,
    InstructorProfileView,
    CoursesIntructorView,
    CourseCategoryView,
    QuizView,
    ContentDeleteView,
    AboutView,
    AllCourseListView,
    ContentCreateUpdateView,
)


app_name = "courses"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("about/", AboutView.as_view(), name="about"),
    path("my-profile/", InstructorProfileView.as_view(), name="profile"),
    path(
        "category/<slug:slug>/", CourseCategoryView.as_view(), name="course_categories"
    ),
    path(
        "instructor-courses/", CoursesIntructorView.as_view(), name="instructor_courses"
    ),
    path("mine/", ManageCourseListView.as_view(), name="manage_course_list"),
    path("create/", CourseCreateView.as_view(), name="course_create"),
    path("<pk>/edit/", CourseUpdateView.as_view(), name="course_edit"),
    path("<pk>/delete", CourseDeleteView.as_view(), name="course_delete"),
    path("<pk>/module/", CourseModuleUpdateView.as_view(), name="course_module_update"),
    path(
        "module/<int:module_id>/content/<model_name>/create/",
        ContentCreateUpdateView.as_view(),
        name="module_content_create",
    ),
    path(
        "module/<int:module_id>/content/<model_name>/<id>/",
        ContentCreateUpdateView.as_view(),
        name="module_content_update",
    ),
    path(
        "content/<int:pk>/delete/",
        ContentDeleteView.as_view(),
        name="module_content_delete",
    ),
    path(
        "module/<int:module_id>/",
        ModuleContentListView.as_view(),
        name="module_content_list",
    ),
    path("module/order/", ModuleOrderView.as_view(), name="module_order"),
    path("content/order/", ContentOrderView.as_view(), name="content_order"),
    path("quiz/", QuizView.as_view(), name="quiz"),
    # path('saveans/', saveans, name='saveans'),
    # path('result/', result, name='result'),
    path("courses-list/", AllCourseListView.as_view(), name="course_list"),
    path(
        "subject/<slug:subject>/", CourseListView.as_view(), name="course_list_subject"
    ),
    path("<slug:slug>/", CourseDetailView.as_view(), name="course_detail"),
]

students/urls.py
from django.urls import path
from .views import (
    StudentRegistrationView, StudentEnrollCourseView, 
    StudentCourseListView, StudentCourseDetailView,
    StudentProfileView, content_is_complete

)

app_name = 'students'
urlpatterns = [
    path('register/', StudentRegistrationView.as_view(), name='student_registration'),
    path('enroll-course/', StudentEnrollCourseView.as_view(), name='student_enroll_course'),
    path('courses/', StudentCourseListView.as_view(), name='student_course_list'),
    path('course/<pk>/', StudentCourseDetailView.as_view(), name='student_course_detail'),
    path('course/<pk>/<module_id>/<object_id>/', StudentCourseDetailView.as_view(), name='student_course_detail_module'),
    path('my-profile/', StudentProfileView.as_view(), name='student_profile'),
    path('content-complete/', content_is_complete, name='content_of_module_complete'),
]

courses/forms.py
from django.forms import ModelForm
from django.forms.models import inlineformset_factory
from .models import (
    Course,
    Module,
    Question,
    Choice,
    Video,
)

ModuleFormSet = inlineformset_factory(
    Course,
    Module,
    fields=["title", "description"],
    extra=2,
    can_delete=True,
)


class VideoForm(ModelForm):
    class Meta:
        model = Video
        fields = ["title", "file", "url"]


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ["question_text", "answer"]


class ChoiceForm(ModelForm):
    class Meta:
        model = Choice
        fields = ["choices_text"]


ChoiceInlineFormSet = inlineformset_factory(
    Question, Choice, form=ChoiceForm, extra=4, can_delete=True
)

courses/views.py
from django.contrib import messages
from django.db.models import Count
from braces.views import CsrfExemptMixin, JsonRequestResponseMixin
from django.apps import apps
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import TemplateResponseMixin
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import (
    TemplateView,
    ListView,
    View,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
)

from users.models import UserProfile
from students.forms import CourseEnrollForm

# ItemBase,
from .models import (
    Course,
    Module,
    Content,
    Subject,
    Question,
    Choice,
    Video,
)
from blog.models import Post
from .forms import (
    # ChoiceFormSet
    ModuleFormSet,
    QuestionForm,
    VideoForm,
    ChoiceInlineFormSet,
)


# Take one or multiple answer in the quiz, and evaluated if are correct
def validating_if_correct(module_quiz, user_answer):
    quiz = Question.objects.get(module=module_quiz)

    if user_answer == quiz.answer:
        return True
    return False


class IndexView(TemplateView):
    template_name = "pages/index.html"

    def get_context_data(self, **kwargs):
        subjects = Subject.objects.all()
        featured_courses = Course.objects.filter(
            featured=True,
        )[:7]
        featured_posts = Post.objects.filter(
            is_publicated=True,
        )[:2]

        try:
            user_profile = UserProfile.objects.get_or_create(user=self.request.user)
        except:
            user_profile = None

        context = super().get_context_data(**kwargs)
        context["profile"] = user_profile
        context["featured_courses"] = featured_courses
        context["featured_posts"] = featured_posts
        context["subjects"] = subjects
        return context


class CourseCategoryView(ListView):

    def get(self, request, slug, *args, **kwargs):
        courses = Course.objects.filter(subject__slug=slug)
        subject = Subject.objects.get(slug=slug)
        context = {"courses": courses, "subject": subject}
        return render(request, "pages/course_category.html", context)


class AboutView(TemplateView):
    template_name = "pages/about.html"


class CoursesIntructorView(PermissionRequiredMixin, TemplateView):
    template_name = (
        "account/profiles/dashboard/instructor/instructor_courses_dashboard.html"
    )
    permission_required = "courses.change_course"


class InstructorProfileView(PermissionRequiredMixin, TemplateView):
    template_name = "account/profiles/dashboard/instructor/instructor_dashboard.html"
    permission_required = "courses.change_course"


class OwnerMixin(object):
    def get_queryset(self):
        qs = super(OwnerMixin, self).get_queryset()
        return qs.filter(owner=self.request.user)


class OwnerEditMixin(object):
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(OwnerEditMixin, self).form_valid(form)


class OwnerCourseMixin(OwnerMixin, LoginRequiredMixin):
    model = Course
    fields = ["subject", "title", "slug", "overview"]
    success_url = reverse_lazy("courses:manage_course_list")


class OwnerCourseEditMixin(OwnerCourseMixin, OwnerEditMixin):
    fields = ["subject", "title", "slug", "overview"]
    success_url = reverse_lazy("courses:manage_course_list")
    template_name = "courses/manage/course/form.html"


class ManageCourseListView(PermissionRequiredMixin, OwnerCourseMixin, ListView):
    # template_name = 'courses/manage/course/list.html'
    template_name = (
        "account/profiles/dashboard/instructor/instructor_courses_dashboard.html"
    )
    permission_required = "courses.change_course"


class AllCourseListView(ListView):
    model = Course
    template_name = "pages/course_list.html"
    context_object_name = "courses"
    paginate_by = 5


class CourseListView(TemplateResponseMixin, View):
    model = Course
    # template_name = 'account/profiles/dashboard/instructor/instructor_courses_dashboard.html'
    template_name = "courses/course/list.html"

    def get(self, request, subject=None):
        subjects = Subject.objects.annotate(total_courses=Count("courses"))
        courses = Course.objects.annotate(total_modules=Count("modules"))

        if subject:
            subject = get_object_or_404(Subject, slug=subject)
            courses = courses.filter(subject=subject)
        return self.render_to_response(
            {"subjects": subjects, "subject": subject, "courses": courses}
        )


class CourseDetailView(DetailView):
    model = Course
    # template_name = 'courses/course/detail.html'
    template_name = "courses/course/course_description.html"

    def get_context_data(self, **kwargs):
        context = super(CourseDetailView, self).get_context_data(**kwargs)
        context["enroll_form"] = CourseEnrollForm(initial={"course": self.object})
        return context


class CourseCreateView(PermissionRequiredMixin, OwnerCourseEditMixin, CreateView):
    permission_required = "courses.add_course"


class CourseUpdateView(PermissionRequiredMixin, OwnerCourseEditMixin, UpdateView):
    permission_required = "courses.change_course"


class CourseDeleteView(PermissionRequiredMixin, OwnerCourseMixin, DeleteView):
    template_name = "courses/manage/course/delete.html"
    success_url = reverse_lazy("courses:manage_course_list")
    permission_required = "courses.delete_course"


class CourseModuleUpdateView(PermissionRequiredMixin, TemplateResponseMixin, View):
    template_name = "courses/manage/module/formset.html"
    course = None
    permission_required = "courses.change_course"

    def get_formset(self, data=None):
        return ModuleFormSet(instance=self.course, data=data)

    def dispatch(self, request, pk):
        self.course = get_object_or_404(Course, id=pk, owner=request.user)
        return super(CourseModuleUpdateView, self).dispatch(request, pk)

    def get(self, request, *args, **kwargs):
        formset = self.get_formset()
        return self.render_to_response({"course": self.course, "formset": formset})

    def post(self, request, *args, **kwargs):
        formset = self.get_formset(data=request.POST)
        if formset.is_valid():
            formset.save()
            return redirect("courses:manage_course_list")
        return self.render_to_response({"course": self.course, "formset": formset})


class ContentDeleteView(View):
    def post(self, request, id):
        content = get_object_or_404(Content, id=id, module__course__owner=request.user)

        module = content.module
        content.item.delete()
        content.delete()
        return redirect("module_content_list", module.id)


class ModuleContentListView(PermissionRequiredMixin, TemplateResponseMixin, View):
    template_name = "courses/manage/module/content_list.html"
    permission_required = "courses.change_course"

    def get(self, request, module_id):
        module = get_object_or_404(Module, id=module_id, course__owner=request.user)
        content = Content.objects.filter(module=module)
        ctx = {
            "content": content,
            "module": module,
        }
        return self.render_to_response(ctx)


class ContentCreateUpdateView(TemplateResponseMixin, View):
    module = None
    model = None
    obj = None
    template_name = None

    def get_model(self, model_name):
        if model_name in ["video", "question"]:
            return apps.get_model(app_label="courses", model_name=model_name)

        return None

    def get_form(self, model, model_name, *args, **kwargs):
        if model_name == "video":
            self.template_name = "courses/video/create_video.html"
            Form = VideoForm(instance=self.obj)
            return Form, None
        else:
            self.template_name = "courses/quiz/form.html"
            Form = QuestionForm(instance=self.obj)
            Formset = ChoiceInlineFormSet(instance=self.obj)

            return Form, Formset

    def dispatch(self, request, module_id, model_name, id=None):
        course = Course.objects.get(modules=module_id)
        if course.owner != request.user:
            raise PermissionDenied

        self.module = get_object_or_404(
            Module, id=module_id, course__owner=request.user
        )
        self.model = self.get_model(model_name)
        if id:
            self.obj = get_object_or_404(self.model, id=id)

        return super(ContentCreateUpdateView, self).dispatch(
            request, module_id, model_name, id
        )

    def get(self, request, module_id, model_name, id=None):
        form, formset = self.get_form(
            self.model,
            model_name,
        )
        return self.render_to_response(
            {"form": form, "formset": formset, "object": self.obj}
        )

    def post(self, request, module_id, model_name, id=None):
        module = Module.objects.get(id=self.module.id)

        if model_name == "video":
            if not id:
                form = VideoForm(self.request.POST, self.request.FILES)
                # form = self.get_form(self.model, instance=self.obj, data=request.POST, files=request.FILES)

                if form.is_valid():
                    video_title = form.cleaned_data.get("title")
                    video_file = form.cleaned_data.get("file")
                    video_url = form.cleaned_data.get("url")

                    video = Video.objects.create(
                        title=video_title, file=video_file, url=video_url
                    )

                    module.has_video = True

templates/courses/course/course_description.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'pages/navbar.html' %}
    {% with subject=course.subject %}
      <div class="container">
        <h1>{{ object.title }}</h1>
        <h2>Overview</h2>

              <video class="content-video" width="500" controls>
                <source class="bostonVideo" src="{% static 'media/boston.mp4' %}" type="video/mp4">
              </video>
            
              <div class="row">
                  <div class="col-8 course-description">
                      <p>{{ object.overview|linebreaks }}</p>
                  </div>
              </div>
              {% if request.user.is_authenticated %}
                <!--form action="{% url 'students:student_enroll_course' %}" method="post">
                    {{ enroll_form }}
                    {% csrf_token %}
                    <input type="submit" class="btn btn-primary" value="Enroll now">
                </form-->
                <a href="{{ object.get_add_to_cart_url }}" class="btn btn-black py-3 px-5">
                  <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart<i class="fas fa-shopping-cart ml-1"></i></button>
                </a>
              {% else %}
                <div class="col-md-12">
                  <a href="{% url 'account_login' %}" class="button">
                    <button type="button" class="btn btn-primary">Subscribete y empieza!</button>
                  </a>
                </div>
              {% endif %}
            

    </div>


<!-- Features Section 1 -->
<section id="features">
	<div class="container">
		<div class="row text-center padding">
			<div class="col-xs-12 col-sm-6 col-md-4 padding">
			<i class="fas fa-plus fa-3x mx-3"></i>
				<h3>+58 Hours</h3>
		<p>Of content to learn.</p>

			</div>
			<div class="col-xs-12 col-sm-6 col-md-4 padding">
		<i class="fa fa-child fa-3x" aria-hidden="true"></i>
				<h3>For Everyone</h3>
		<p>Built with the leates version of Django, teris asterum campen mellis eberatun taram</p>

			</div>
			<div class="col-sm-12 col-md-4 padding">
		<i class="fa fa-search-plus fa-3x" aria-hidden="true"></i>
				<h3>Searching</h3>
		<p>Built with the leates version of css3, teris asterum campen mellis eberatun taram</p>

			</div>
		</div>
		<hr class="my-4">
	</div>
</section>
<!-- Features Section 1 -->

<!-- Description Section -->
<section id="about" class="about">
    <div class="container">

      <div class="row content">
        <div class="col-lg-6">
          <h2>Eum ipsam laborum deleniti velitena</h2>
          <h3>Voluptatem dignissimos provident quasi corporis voluptates sit assum perenda sruen jonee trave</h3>
        </div>
        <div class="col-lg-6 pt-4 pt-lg-0">
          <p>
            Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
            velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
            culpa qui officia deserunt mollit anim id est laborum
          </p>
          <ul class="fa-ul">
            <li><span class="fa-li"><i class="fa fa-check"></i></span> Ullamco laboris nisi ut aliquip ex ea commodo consequa</li>
            <li><span class="fa-li"><i class="fa fa-check"></i></span> Duis aute irure dolor in reprehenderit in voluptate velit</li>
            <li><span class="fa-li"><i class="fa fa-check"></i></span> Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in</li>
          </ul>
          <p class="font-italic">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
            magna aliqua.
          </p>
        </div>
      </div>

    </div>
  </section>
<!-- End Description Section -->
{% endwith %}
{% endblock content %}

templates/courses/course/list.html
{% extends 'base.html' %}

{% block title %}
    {% if subject %}
        {{ subject.title }} courses
    {% else %}
        All courses
    {% endif %}
{% endblock title %}


{% block content %}
<h1>
    {% if subject %}
        {{ subject.title }} courses
    {% else %}
        All courses
    {% endif %}
</h1>
<div class="contents">
    <h3>Subjects</h3>
    <ul id="modules">
        <li {% if not subject %}class="selected"{% endif %}>
            <a href="{% url 'courses:course_list' %}">All</a>
        </li>
        {% for s in subjects %}
            <li {% if subject == s %}class="selected"{% endif %}>
                <a href="{% url 'courses:course_list_subject' s.slug %}">
                    {{ s.title }}
                    <br><span>{{ s.total_courses }} courses</span>
                </a>
            </li>
        {% endfor %}
    </ul>
</div>
<div class="module">
    {% for course in courses %}
        {% with subject=course.subject %}
            <h3><a href="{% url 'courses:course_detail' course.slug %}">{{ course.title }}</a></h3>
            <p>
                <a href="{% url 'courses:course_list_subject' subject.slug %}">
                    {{ subject }}
                </a>
                {{ course.total_modules }} modules.
                Instructor: {{ course.owner.get_full_name }}
            </p>
        {% endwith %}
    {% endfor %}
</div>
{% endblock %}