blog/urls.py
from django.urls import path 

from blog.views import (
	BlogPageView, 
	# SearchResultsListView, 
    # CategoryPageView,
	PostDetailView,
)


app_name = 'blog'
urlpatterns = [

 	path('blog/', BlogPageView.as_view(), name='blog'),
 	path('blog/<slug:slug>', PostDetailView.as_view(), name='blog_post_detail'),
 	# path('search/', SearchResultsListView.as_view(), name='search_results'),
	# path('category/<int:pk>', CategoryPageView.as_view(), name='category'),

]

courses/urls.py
from django.urls import path

from .views import (
    ManageCourseListView,
    CourseCreateView,
    CourseUpdateView,
    CourseDeleteView,
    CourseModuleUpdateView,
    ModuleContentListView,
    ModuleOrderView,
    ContentOrderView,
    CourseListView,
    CourseDetailView,
    IndexView,
    InstructorProfileView,
    CoursesIntructorView,
    CourseCategoryView,
    QuizView,
    ContentDeleteView,
    AboutView,
    AllCourseListView,
    ContentCreateUpdateView,
)


app_name = "courses"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("about/", AboutView.as_view(), name="about"),
    path("my-profile/", InstructorProfileView.as_view(), name="profile"),
    path(
        "category/<slug:slug>/", CourseCategoryView.as_view(), name="course_categories"
    ),
    path(
        "instructor-courses/", CoursesIntructorView.as_view(), name="instructor_courses"
    ),
    path("mine/", ManageCourseListView.as_view(), name="manage_course_list"),
    path("create/", CourseCreateView.as_view(), name="course_create"),
    path("<pk>/edit/", CourseUpdateView.as_view(), name="course_edit"),
    path("<pk>/delete", CourseDeleteView.as_view(), name="course_delete"),
    path("<pk>/module/", CourseModuleUpdateView.as_view(), name="course_module_update"),
    path(
        "module/<int:module_id>/content/<model_name>/create/",
        ContentCreateUpdateView.as_view(),
        name="module_content_create",
    ),
    path(
        "module/<int:module_id>/content/<model_name>/<id>/",
        ContentCreateUpdateView.as_view(),
        name="module_content_update",
    ),
    path(
        "content/<int:pk>/delete/",
        ContentDeleteView.as_view(),
        name="module_content_delete",
    ),
    path(
        "module/<int:module_id>/",
        ModuleContentListView.as_view(),
        name="module_content_list",
    ),
    path("module/order/", ModuleOrderView.as_view(), name="module_order"),
    path("content/order/", ContentOrderView.as_view(), name="content_order"),
    path("quiz/", QuizView.as_view(), name="quiz"),
    # path('saveans/', saveans, name='saveans'),
    # path('result/', result, name='result'),
    path("courses-list/", AllCourseListView.as_view(), name="course_list"),
    path(
        "subject/<slug:subject>/", CourseListView.as_view(), name="course_list_subject"
    ),
    path("<slug:slug>/", CourseDetailView.as_view(), name="course_detail"),
]

payment/urls.py
from django.urls import path

from .views import (
    CartPageView, add_to_cart,
    remove_from_cart, CheckoutView,
    PaymentView, payment_complete
)

app_name = 'payment'
urlpatterns = [
    path('cart/', CartPageView.as_view(), name='cart'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('payment-complete/', payment_complete, name='payment_complete'),
]

students/urls.py
from django.urls import path
from .views import (
    StudentRegistrationView, StudentEnrollCourseView, 
    StudentCourseListView, StudentCourseDetailView,
    StudentProfileView, content_is_complete

)

app_name = 'students'
urlpatterns = [
    path('register/', StudentRegistrationView.as_view(), name='student_registration'),
    path('enroll-course/', StudentEnrollCourseView.as_view(), name='student_enroll_course'),
    path('courses/', StudentCourseListView.as_view(), name='student_course_list'),
    path('course/<pk>/', StudentCourseDetailView.as_view(), name='student_course_detail'),
    path('course/<pk>/<module_id>/<object_id>/', StudentCourseDetailView.as_view(), name='student_course_detail_module'),
    path('my-profile/', StudentProfileView.as_view(), name='student_profile'),
    path('content-complete/', content_is_complete, name='content_of_module_complete'),
]

courses/models.py
from django.db import models
from django.urls import reverse
from django.template.loader import render_to_string
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from .fields import OrderField

User = get_user_model()


class Subject(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(blank=True, upload_to="images/")
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("courses:course_categories", kwargs={"slug": self.slug})


class Course(models.Model):
    owner = models.ForeignKey(
        User, related_name="courses_created", on_delete=models.CASCADE
    )
    subject = models.ForeignKey(
        Subject, related_name="courses", on_delete=models.CASCADE
    )
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    overview = models.TextField()
    image = models.ImageField(
        "Imagen Referencial", upload_to="imagenes/", max_length=255
    )
    students = models.ManyToManyField(User, related_name="courses_joined", blank=True)
    price = models.FloatField()
    created = models.DateTimeField(auto_now_add=True)
    featured = models.BooleanField(default=False)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("courses:course_detail", kwargs={"slug": self.slug})

    def get_add_to_cart_url(self):
        return reverse("payment:add-to-cart", kwargs={"slug": self.slug})

    def get_remove_from_cart_url(self):
        return reverse("payment:remove-from-cart", kwargs={"slug": self.slug})


class Module(models.Model):
    course = models.ForeignKey(Course, related_name="modules", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    order = OrderField(blank=True, for_fields=["course"])
    has_video = models.BooleanField(default=False)
    has_quiz = models.BooleanField(default=False)

    class Meta:
        ordering = ["order"]

    def __str__(self):
        return "{}. {}".format(self.order, self.title)


class Video(models.Model):
    title = models.CharField(max_length=250)
    file = models.FileField(upload_to="files")
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

    # def render(self):
    #     return render_to_string('courses/content/{}.html'.format(self._meta.model_name), {'item': self})
    def render(self):
        return render_to_string("courses/content/video.html", {"item": self})


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    answer = models.CharField(max_length=200)

    def __str__(self):
        return self.question_text

    # def render(self):
    #     return render_to_string('courses/content/{}.html'.format(self._meta.model_name), {'item': self})
    def render(self):
        return render_to_string("courses/quiz/quiz.html", {"item": self})


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choices_text = models.CharField(max_length=200)

    def __str__(self):
        return self.choices_text


class Content(models.Model):
    module = models.ForeignKey(
        Module, related_name="contents", on_delete=models.CASCADE
    )
    # video = models.ForeignKey(Video, on_delete=models.CASCADE, blank=True, null=True)
    # quiz = models.ForeignKey(Question, on_delete=models.CASCADE, blank=True, null=True)
    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
        limit_choices_to={"model__in": ("video", "question")},
    )
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey("content_type", "object_id")

    def __str__(self):
        return "content of {}".format(self.module.title)


class ContentIsComplete(models.Model):
    """This is a Class to list which content is completed for
    a student"""

    content = models.ForeignKey(Content, on_delete=models.CASCADE)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    is_complete = models.BooleanField(default=False)


class InCourse(models.Model):
    """
    This is a object that store the progress of a student in a course
    """

    student = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    progress = models.PositiveIntegerField(default=0)

    def __str__(self):
        return "{} have a {}% of {} course completed".format(
            self.student.email,
            self.progress,
            self.course.title,
        )

    def add_progress(self, course_id):
        total_content = Content.objects.filter(module__course=course_id).count()
        content_porcent = (1 / total_content) * 100
        self.progress += content_porcent

payment/views.py
import json
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import (
    TemplateView, View 
)
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages

from .models import OrderCourse, Order, Address, Payment
from .forms import CheckoutForm
from courses.models import Course




class CartPageView(View):

    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order,
            }
            return render(self.request, 'pages/cart.html', context)
        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have an active order")
            return redirect("/")


class CheckoutView(View):

    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            form = CheckoutForm()
            context = {
                'form': form,
                'order': order,
            }

            shipping_address_qs = Address.objects.filter(
                user=self.request.user,
                address_type='S',
                default=True
            )

            billing_address_qs = Address.objects.filter(
                user=self.request.user,
                address_type='B',
                default=True
            )

            return render(self.request, "pages/checkout.html", context)
        except ObjectDoesNotExist:
            messages.info(self.request, 'You do not have an active order')
            return redirect("payment:cart")
    
    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)

        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():
                street_address= form.cleaned_data.get('street_address')
                apartment_address = form.cleaned_data.get('apartment_address')
                country = form.cleaned_data.get('country')
                zip_code = form.cleaned_data.get('zip_code')

                payment_option = form.cleaned_data.get('payment_option')

                billing_address = Address(
                    user=self.request.user,
                    street_address=street_address,
                    apartment_address=apartment_address,
                    country=country,
                    zip_code=zip_code,
                    address_type='B'
                )

                billing_address.save()
                order.billing_address = billing_address
                order.payment_option = payment_option
                order.save()

                if payment_option == 'S':
                    return redirect('payment:payment', payment_option="PayPal")
                elif payment_option == 'P':
                    return redirect('payment:payment', payment_option='PayPal')
                else:
                    messages.warning(self.request, 'Invalid payment option')
                    return redirect('payment:checkout')
        
        except ObjectDoesNotExist:
            messages.error(self.request, 'You do not have an active order')
            return redirect("payment:cart")


class PaymentView(View):

    def get(self, *args, payment_option, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        context = {
            'order': order,
            'payment_option': payment_option,
        }
        return render(self.request, 'pages/payment.html', context)


def payment_complete(request):
    body = json.loads(request.body)
    user = request.user
    order = Order.objects.get(
        user=user, ordered=False, id=body['orderID']
    )
    if order:
        payment = Payment(
            user=user,
            charge_id=body['payID'],
            amount=order.get_total()
        )
        payment.save()

        #Assign the paymet to the order
        order_items = order.items.all()
        order_items.update(ordered=True)

        for item in order_items:
        # Add user to courses
            course = Course.objects.get(id=item.id)
            course.students.add(user)
            item.save()
        
        order.ordered = True
        order.payment = payment
        order.save()

        messages.info(request, "The payment was successfull")
        return redirect('students:student_course_list')
    else:
        messages.info(request, "A serius error accourred. We have been notified")
        return redirect('/')

@login_required
def add_to_cart(request, slug):
    course = get_object_or_404(Course, slug=slug)
    
    # Evaluated if user is already enrolled for this course.
    user_in = Course.objects.filter(id=course.id, students=request.user)
    if user_in.exists():
        messages.info(request, "You are already enrolled for this package")
        return redirect("courses:index")

    order_item, created = OrderCourse.objects.get_or_create(
                                                            course=course,
                                                            user=request.user,
                                                            ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]
        # Check if the order item is in the order
        if order.items.filter(course__slug=course.slug).exists():
            # order_item.quantity += 1
            order_item.save()
            messages.info(request, "This item quantity was updated.")
            return redirect("payment:cart")
        else:
            order.items.add(order_item)
            messages.info(request, "This item was added to your cart.")
            return redirect("payment:cart")
    else:
        order = Order.objects.create(
            user=request.user,
        )
        order.items.add(order_item)
        messages.info(request, "This item was added to your cart.")
        return redirect("payment:cart")

@login_required
def remove_from_cart(request, slug):
    course = get_object_or_404(Course, slug=slug)
    order_qs = Order.objects.filter(
                                    user=request.user,
                                    ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # Check if the order item is in the order
        if order.items.filter(course__slug=course.slug).exists():
            order_item = OrderCourse.objects.filter(
                                                    course=course,
                                                    user=request.user,
                                                    ordered=False,
            )[0]
            order.items.remove(order_item)
            order_item.delete()
            messages.info(request, "This item was removed from your cart.")
            return redirect("payment:cart")
        else:
            messages.info(request, "This item not in your cart.")
            return redirect("courses:course_detail", slug=slug)
    else:
        messages.info(request, "You do not have an activate order.")
        return redirect("courses:course_detail", slug=slug)

templates/pages/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% include 'pages/navbar.html' %}
      <div class="site-section">
        <div class="container">
            <div class="row mb-5">
              <div class="col-md-12">
                <div class="site-blocks-table">
                  <table class="table table-bordered">
                    <thead>
                      <tr>
                        <!--th class="product-thumbnail text-center">Image</th-->
                        <th class="product-name text-center">Product</th>
                        <th class="product-price text-center">Price</th>
                        <!--th class="product-quantity text-center">Quantity</th-->
                        <th class="product-total text-center">Total</th>
                        <th class="product-remove text-center">Remove</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for order_item in object.items.all %}
                        <!-- <tr>{#% thumbnail order_item.item.image "150" as im %#}
                            <td class="product-thumbnail text-center">
                              <img src="{#% if im %#}{#{ im.url }#}{#% else %#}{#% static 'img/no_image.png' %#}{#% endif %#}" alt="Image" class="img-fluid">
                            </td> -->
                          {#% endthumbnail %#}
                          <td class="product-name text-center">
                            <h2 class="h5 text-black">{{ order_item.course.title }}</h2>
                          </td>
                          <td class="text-center">{{ order_item.course.price }}</td>
                          <!-- <td>
                            <div class="input-group mb-3" style="max-width: 120px;">
                              <div class="input-group-prepend text-center">
                                <a href="{#% url 'shop:remove-single-item-from-cart' order_item.item.slug %#}"><button class="btn btn-outline-primary js-btn-minus" type="button">&minus;</button></a-->
                              </div>
                              <input type="text" class="form-control text-center" value="{#{ order_item.quantity }#}" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                              <div class="input-group-append text-center">
                                <!--a href="{#% url 'shop:add-to-cart' order_item.item.slug %#}"><button class="btn btn-outline-primary js-btn-plus text-center" type="button">&plus;</button></a>
                              </div>
                            </div>
                          </td-->
                          <td class="text-center">{{ order_item.get_total_items_price }}</td>
                          <td class="text-center"><a href="{% url 'payment:remove-from-cart' order_item.course.slug %}" class="btn btn-primary btn-sm">X</a></td>
                        </tr>
                      {% empty %}
                        <tr>
                            <td colspan='5'>Your cart is empty
                            </td>
                        </tr>
                      {% endfor %} 
                    </tbody>
                  </table>
                </div>
          </div>
        </div>

          <div class="row">
            <div class="col-md-6">
              <div class="row mb-5">
                <!--div class="col-md-6 mb-3 mb-md-0">
                  <button class="btn btn-primary btn-sm btn-block">Update Cart</button>
                </div-->
                <div class="col-md-6">
                  <a href="{% url 'courses:course_list' %}"><button class="btn btn-outline-primary btn-sm btn-block">Continue Shopping</button></a>
                </div>
              </div>
            </div>
            <div class="col-md-6 pl-5">
              <div class="row justify-content-end">
                <div class="col-md-7">
                  <div class="row">
                    <div class="col-md-12 text-right border-bottom mb-5">
                      <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                    </div>
                  </div>
                  <div class="row mb-3">
                    <div class="col-md-6">
                      <span class="text-black">Subtotal</span>
                    </div>
                    <div class="col-md-6 text-right">
                      <strong class="text-black">${{ object.get_total }}</strong>
                    </div>
                  </div>
                  <div class="row mb-5">
                    <div class="col-md-6">
                      <span class="text-black">Total</span>
                    </div>
                    <div class="col-md-6 text-right">
                      <strong class="text-black">${{ object.get_total }}</strong>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-md-12">
                      <a href="{% url 'payment:checkout' %}"><button class="btn btn-primary btn-lg py-3 btn-block">Proceed To Checkout</button></a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% include 'pages/footer.html' %}
{% endblock content %}

templates/pages/header.html
{% load static %}
{#% load cart_template_tags %#}

<header>
        <div class="container-fluid p-0">
            <nav class="navbar navbar-expand-lg fixed-top">
                <a class="navbar-brand" href="{% url 'courses:index' %}"><i class="fas fa-book-reader fa-3x mx-3"></i>E-learningX</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <div class="mr-auto"></div>
                  <ul class="navbar-nav">
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'courses:index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'courses:course_list' %}">Courses</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'courses:about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:blog' %}">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link waves-effect" href="{% url 'payment:cart' %}">
                        <span class="badge red z-depth-1 mr-1">{#{ request.user|cart_item_count }#}</span>
                        <i class="fas fa-shopping-cart"></i>
                        <span class="clearfix d-none d-sm-inline-block">Cart</span>
                      </a>
                    </li>
                    {% if request.user.is_authenticated %}
                      {% if perms.courses.change_course %}
                        <li class="nav-item">
                          <a href="{% url 'courses:manage_course_list' %}"><i class="far fa-user-circle fa-2x" aria-hidden="true"></i></a>
                        </li>
                      {% else %}
                        <li class="nav-item">
                          <a href="{% url 'students:student_course_list' %}"><i class="far fa-user-circle fa-2x" aria-hidden="true"></i></a>
                        </li>
                      {% endif %}
                        <li class="nav-item">
                            <span class="font-weight-bold">Hi {{ user.email }}!</span>
                            <a href="{% url 'account_logout' %}">Log Out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a href="{% url 'account_login' %}"><button type="button" class="btn btn-light">Log In</button></a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'account_signup' %}"><button type="button" class="btn btn-primary">Sign Up</button></a>
                        </li>
                    {% endif %}
                  </ul>
                </div>
              </nav>
        </div>

        <div class="container text-center">
            <div class="row">
                <div class="col-md-7 col-sm-12">
                        <h1>Online learning <br> platform</h1>
                        <p> Build skills with courses, certificates, and degrees online from world-class 
                          universities and companies
                        </p>
                        {% if user.is_authenticated %}
                          <a href="{% url 'courses:course_list' %}"><button class="btn btn-light px-5 py-2">
                          Discover more courses</button></a>
                        {% else %}
                          <a href="{% url 'account_signup' %}"><button class="btn btn-light px-5 py-2">Join For Free</button></a>
                        {% endif %}
                </div>
                    <div class="col-md-5 col-sm-12 h-25">
                        <img src="{% static 'img/hero-learning.png' %}" alt="Guys learning">
                    </div>
            </div>
        </div>
    </header>


templates/pages/navbar.html
{% load static %}
{# % load cart_template_tags % #}

<header>
  <div class="container-fluid p-0">
    <nav class="navbar navbar-expand-lg fixed-top">
      <a class="navbar-brand" href="{% url 'courses:index' %}"><i class="fas fa-book-reader fa-3x mx-3"></i>E-learningX</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <div class="mr-auto"></div>
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'courses:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'courses:course_list' %}">Courses</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'courses:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:blog' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'payment:cart' %}">
              <span class="badge red z-depth-1 mr-1">{# { request.user|cart_item_count } #}</span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block">Cart</span>
            </a>
          </li>
          {% if request.user.is_authenticated %}
            {% if perms.courses.change_course %}
              <li class="nav-item">
                <a href="{% url 'courses:manage_course_list' %}"><i class="far fa-user-circle fa-2x" aria-hidden="true"></i></a>
              </li>
            {% else %}
              <li class="nav-item">
                <a href="{% url 'students:student_course_list' %}"><i class="far fa-user-circle fa-2x" aria-hidden="true"></i> asdasd</a>
              </li>
            {% endif %}
            <li class="nav-item">
              <span class="font-weight-bold">Hi {{ user.email }}!</span>
              <a href="{% url 'account_logout' %}">Log Out</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a href="{% url 'account_login' %}"><button type="button" class="btn btn-light">Log In</button></a>
            </li>
            <li class="nav-item">
              <a href="{% url 'account_signup' %}"><button type="button" class="btn btn-primary">Sign Up</button></a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </div>
</header>