blog/urls.py
from django.urls import path 

from blog.views import (
	BlogPageView, 
	# SearchResultsListView, 
    # CategoryPageView,
	PostDetailView,
)


app_name = 'blog'
urlpatterns = [

 	path('blog/', BlogPageView.as_view(), name='blog'),
 	path('blog/<slug:slug>', PostDetailView.as_view(), name='blog_post_detail'),
 	# path('search/', SearchResultsListView.as_view(), name='search_results'),
	# path('category/<int:pk>', CategoryPageView.as_view(), name='category'),

]

students/urls.py
from django.urls import path
from .views import (
    StudentRegistrationView, StudentEnrollCourseView, 
    StudentCourseListView, StudentCourseDetailView,
    StudentProfileView, content_is_complete

)

app_name = 'students'
urlpatterns = [
    path('register/', StudentRegistrationView.as_view(), name='student_registration'),
    path('enroll-course/', StudentEnrollCourseView.as_view(), name='student_enroll_course'),
    path('courses/', StudentCourseListView.as_view(), name='student_course_list'),
    path('course/<pk>/', StudentCourseDetailView.as_view(), name='student_course_detail'),
    path('course/<pk>/<module_id>/<object_id>/', StudentCourseDetailView.as_view(), name='student_course_detail_module'),
    path('my-profile/', StudentProfileView.as_view(), name='student_profile'),
    path('content-complete/', content_is_complete, name='content_of_module_complete'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-learningX</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <!--Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css" integrity="sha512-1cK78a1o+ht2JcaW6g8OXYwqpev9+6GqOkz9xmBN9iUUhIndKtxwILGWYOSibOKjLsEdjyjZvYDq/cZwNeak0w==" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    {% block extra_head %}
    {% endblock extra_head %}
</head>
<body>
    {% if messages %}
    {% for message in messages %}
     <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
  {% endif %}

    {% block content %}
    {% endblock content %}

    <!-- End Header section -->



    <!-- Project JavaScript -->
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <!-- <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script> -->
    <script src="{% static 'js/all.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.mousewheel.min.js' %}"></script>


   {% block extra_javascript %}
   {% endblock extra_javascript %}
   <script>
    $(window).on('scroll', function(){
        if($(window).scrollTop()){
            $('.navbar').addClass('black');
        }
        else{
            $('.navbar').removeClass('black');
        }
    });
    $(document).ready(function(){
            $(".owl-carousel").owlCarousel( {
                autoplay: false,
                autoplayHoverPause: true,
                items: 3,
                nav: true,
                dots: false,
                loop: true,
                lazyload: true,
                margin:5,
                stagePadding: 5,
                responsive: {
                    0: {
                        items: 1,
                        // dots: false,
                    },
                    485: {
                        items: 2,
                        // dots: false,
                    },
                    720: {
                        items: 3,
                        // dots: false,
                    },
                    960: {
                        items: 4,
                        // dots: false,
                    },
                    1200: {
                        items: 3,
                        // dots: false,
                    }
                }
            });
        });

        $('.owl-carousel').on('mousewheel', '.owl-stage', function (e) {
            if (e.deltaY>0) {
                $('.owl.carousel').trigger('next.owl');
            } else {
                $('owl.carousel').trigger('prev.owl');
            }
            e.preventDefault();
        });


   </script>
          <script type="text/javascript">
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie !== "") {
                var cookies = document.cookie.split(";");
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === name + "=") {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                    }
                }
                }
                return cookieValue;
            }
            $(document).ready(function(){ 
             
               $(".content-video-2").one('focus', function(e){
                 e.preventDefault();
                   $.ajax({
                      url: "{% url 'students:content_of_module_complete' %}",
                      type: 'post',
                      headers: {
                        "Content-type": "application/json",
                        "X-CSRFToken": getCookie("csrftoken"),
                      },
                      data: JSON.stringify({
                        content_id: "{{ content.id }}",
                        course_id: "{{ course.id }}",
                      }),
                      success: function(response){
                       $("#myDIV{{ content.id }}").append("<i class='fa fa-check fa-1x'></i>");
                      }
                   });
                 });
               });
           </script>
           
</body>
</html>