blog/urls.py
from django.urls import path 

from blog.views import (
	BlogPageView, 
	# SearchResultsListView, 
    # CategoryPageView,
	PostDetailView,
)


app_name = 'blog'
urlpatterns = [

 	path('blog/', BlogPageView.as_view(), name='blog'),
 	path('blog/<slug:slug>', PostDetailView.as_view(), name='blog_post_detail'),
 	# path('search/', SearchResultsListView.as_view(), name='search_results'),
	# path('category/<int:pk>', CategoryPageView.as_view(), name='category'),

]

courses/urls.py
from django.urls import path

from .views import (
    ManageCourseListView,
    CourseCreateView,
    CourseUpdateView,
    CourseDeleteView,
    CourseModuleUpdateView,
    ModuleContentListView,
    ModuleOrderView,
    ContentOrderView,
    CourseListView,
    CourseDetailView,
    IndexView,
    InstructorProfileView,
    CoursesIntructorView,
    CourseCategoryView,
    QuizView,
    ContentDeleteView,
    AboutView,
    AllCourseListView,
    ContentCreateUpdateView,
)


app_name = "courses"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("about/", AboutView.as_view(), name="about"),
    path("my-profile/", InstructorProfileView.as_view(), name="profile"),
    path(
        "category/<slug:slug>/", CourseCategoryView.as_view(), name="course_categories"
    ),
    path(
        "instructor-courses/", CoursesIntructorView.as_view(), name="instructor_courses"
    ),
    path("mine/", ManageCourseListView.as_view(), name="manage_course_list"),
    path("create/", CourseCreateView.as_view(), name="course_create"),
    path("<pk>/edit/", CourseUpdateView.as_view(), name="course_edit"),
    path("<pk>/delete", CourseDeleteView.as_view(), name="course_delete"),
    path("<pk>/module/", CourseModuleUpdateView.as_view(), name="course_module_update"),
    path(
        "module/<int:module_id>/content/<model_name>/create/",
        ContentCreateUpdateView.as_view(),
        name="module_content_create",
    ),
    path(
        "module/<int:module_id>/content/<model_name>/<id>/",
        ContentCreateUpdateView.as_view(),
        name="module_content_update",
    ),
    path(
        "content/<int:pk>/delete/",
        ContentDeleteView.as_view(),
        name="module_content_delete",
    ),
    path(
        "module/<int:module_id>/",
        ModuleContentListView.as_view(),
        name="module_content_list",
    ),
    path("module/order/", ModuleOrderView.as_view(), name="module_order"),
    path("content/order/", ContentOrderView.as_view(), name="content_order"),
    path("quiz/", QuizView.as_view(), name="quiz"),
    # path('saveans/', saveans, name='saveans'),
    # path('result/', result, name='result'),
    path("courses-list/", AllCourseListView.as_view(), name="course_list"),
    path(
        "subject/<slug:subject>/", CourseListView.as_view(), name="course_list_subject"
    ),
    path("<slug:slug>/", CourseDetailView.as_view(), name="course_detail"),
]

students/urls.py
from django.urls import path
from .views import (
    StudentRegistrationView, StudentEnrollCourseView, 
    StudentCourseListView, StudentCourseDetailView,
    StudentProfileView, content_is_complete

)

app_name = 'students'
urlpatterns = [
    path('register/', StudentRegistrationView.as_view(), name='student_registration'),
    path('enroll-course/', StudentEnrollCourseView.as_view(), name='student_enroll_course'),
    path('courses/', StudentCourseListView.as_view(), name='student_course_list'),
    path('course/<pk>/', StudentCourseDetailView.as_view(), name='student_course_detail'),
    path('course/<pk>/<module_id>/<object_id>/', StudentCourseDetailView.as_view(), name='student_course_detail_module'),
    path('my-profile/', StudentProfileView.as_view(), name='student_profile'),
    path('content-complete/', content_is_complete, name='content_of_module_complete'),
]

students/forms.py
from django import forms

from courses.models import Course


class CourseEnrollForm(forms.Form):
    course = forms.ModelChoiceField(
        queryset=Course.objects.all(), widget=forms.HiddenInput
    )

students/views.py
import json
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse,JsonResponse
from django.views.generic import (
    CreateView, FormView, 
    ListView, DetailView,
    TemplateView, View
)


from .forms import CourseEnrollForm
from users.forms import CustomUserCreationForm
from courses.models import (
    Course, Content, 
    ContentIsComplete, InCourse 
)




class StudentRegistrationView(CreateView):
    template_name = 'students/student/registration.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('students:student_course_list')


    def form_valid(self, form):
        result = super(StudentRegistrationView, self).form_valid(form)
        return result


class StudentEnrollCourseView(LoginRequiredMixin, FormView):
    course = None
    form_class = CourseEnrollForm


    def form_valid(self, form):
        self.course = form.cleaned_data['course']
        self.course.students.add(self.request.user)
        return super(StudentEnrollCourseView, self).form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('students:student_course_detail', args=[self.course.id])


class StudentCourseListView(LoginRequiredMixin, ListView):
    model = Course
    # template_name = 'students/course/list.html'
    template_name = 'account/profiles/dashboard/students/students_courses_dashboard.html'
    context_object_name = 'courses'
    

    def get_queryset(self):
        qs = super(StudentCourseListView, self).get_queryset()
        return qs.filter(students__in=[self.request.user])


class StudentCourseDetailView(DetailView):
    model = Course
    # template_name = 'students/course/detail.html'
    template_name = 'account/profiles/dashboard/students/students_courses_content.html'
    

    def get_queryset(self):
        qs = super(StudentCourseDetailView, self).get_queryset()
        return qs.filter(students__in=[self.request.user])
    
    def get_context_data(self, *args, **kwargs):
        context = super(StudentCourseDetailView, self).get_context_data(**kwargs)
        # get course object
        context['course'] = self.get_object()
        if 'object_id' in self.kwargs:
            # get current module
            context['content'] = Content.objects.get(id=self.kwargs['object_id'])
        else:
            pass
        return context


class StudentProfileView(TemplateView):
    template_name = 'account/profiles/dashboard/students/students_dashboard.html'




def content_is_complete(request):
    if request.is_ajax():
        data_request = json.loads(request.body)
        student = request.user

        content_complete, created = ContentIsComplete.objects.get_or_create(
            content_id=data_request['content_id'],
            student_id=student.id,
            is_complete=True,
        )
        course_progress, created = InCourse.objects.get_or_create(
            student=student,
            course=data_request['course_id'],
        )
        course_progress.add_progress(data_request['course_id'])
        course_progress.save()
        content_complete.save()

        return HttpResponse('')

templates/students/course/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.title }}
{% endblock title %}


{% block content %}
    <h1>
        {{ module.title }}
    </h1>
    <div class="contents">
        <h3>Modules</h3>
        <ul class="modules">
            {% for m in object.modules.all %}
                <li data-id="{{ m.id }}" {% if m == module %}class="selected" {% endif %}>
                    <a href="{% url 'students:student_course_detail_module' object.id m.id %}">
                        <span>
                            Module <span class="order">{{ m.order|add:1 }}</span>
                        </span>
                        <br>
                        {{ m.title }}
                    </a>
                </li>
            {% empty %}
                <li>No modules yet.</li>
            {% endfor %}
        </ul>
    </div>
    <div class="module">
        {% for content in module.contents.all %}
            {% with item=content.item %}
                <h2>{{ item.title }}</h2>
                {{ item.render }}
            {% endwith %}
        {% endfor %}
    </div>
{% endblock %}

templates/students/course/list.html
{% extends 'base.html' %}

{% block title %}My courses{% endblock title %}


{% block content %}
    <h1>My courses</h1>

    <div class="module">
        {% for course in object_list %}
            <div class="course-info">
                <h3>{{ course.title }}</h3>
                <p><a href="{% url 'students:student_course_detail' course.id %}">
                    Access contents
                </a></p>
            </div>
        {% empty %}
            <p>
                Your are not enrolled in any courses yet.
                <a href="{% url 'courses:course_list' %}">Browse courses</a>
                to enroll in a course
            </p>
        {% endfor %}
    </div>
{% endblock content %}